# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 64 # 内存大小，单位MB
  timeout: 86400 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  installDependency: true # 是否在线安装依赖
  events: #触发器
    - timer:  #燃动夏季
        parameters:
          name: feedPets_moneyTree_plantBean_dreamFactory_jdfactory_healthenergy
          cronExpression: "0 3 0,6-23/1 * * * *"
          enable: true
          argument: jd_summer_movement
    - timer: #燃动夏季领取会员奖励（一次性）
        parameters:
          name: pigPet_syj_kd_jdzz_nzmh_necklace_nzmh_djjl_ddly_lsj
          cronExpression: "0 20 0,7,20 * * * *"
          enable: true
          argument: jd_summer_movement_card
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
